kitapsoresi/kitapsoresi/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from kitapsoresi import settings
from messenger.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('messenger.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = error400
handler403 = error403
handler404 = error404
handler500 = error500

kitapsoresi/messenger/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('about/', about, name='about'),
    path('registeration/', registrationPage, name='registrationPage'),

    path('books/author/<slug:author_slug>', BooksAuthor.as_view(), name='author'),
    path('books/', BookHome.as_view(), name='booksPage'),
    path('books/genre/<slug:genre_slug>', BooksGenre.as_view(), name='genre'),

    path('addpage/', AddBook.as_view(), name='addbook'),

    path('book/<slug:book_slug>', ShowBook.as_view(), name='book'),
]

kitapsoresi/messenger/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Genre(models.Model):
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('genre', kwargs={'genre_slug': self.slug})

    class Meta:
        verbose_name = 'Жанры книг'
        verbose_name_plural = 'Жанры книг'
        ordering = ['name']


class Author(models.Model):
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    name = models.CharField(max_length=200, help_text="Enter a book Author")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('author', kwargs={'author_slug': self.slug})

    class Meta:
        verbose_name = 'Авторы книг'
        verbose_name_plural = 'Автор книги'
        ordering = ['name']


class Books(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название книги")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    author = models.ForeignKey(Author, on_delete=models.PROTECT)
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/")
    description = models.TextField(blank=True)
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    price = models.IntegerField(blank=False)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('book', kwargs={'book_slug': self.slug})

    class Meta:
        verbose_name = 'Список книг'
        verbose_name_plural = 'Список книг'
        ordering = ['name']


class Friends(models.Model):
    user_id = models.IntegerField(blank=False)  # обязательно к заполнению, заполняется автоматически в бэке
    follower_id = models.IntegerField(blank=False)  # обязательно к заполнению, заполняется автоматически в бэке


class News(models.Model):
    author_id = models.IntegerField()
    time = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to="newsPhotos/%Y/%m/%d")
    text = models.TextField(blank=True)  # не обязательно к заполнению
    bookId = models.IntegerField(blank=True)  # не обязательно к заполнению
    saveStatus = models.BooleanField(default=False)


class StarList(models.Model):
    user_id = models.IntegerField()
    post_id = models.IntegerField(blank=True)  # не обязательно к заполнению, заполняется автоматически в бэке
    book_id = models.IntegerField(blank=True)  # не обязательно к заполнению, заполняется автоматически в бэке


class WishList(models.Model):
    user_id = models.IntegerField()
    book_id = models.IntegerField()
    comment = models.TextField(blank=True)


class Messages(models.Model):
    author_id = models.IntegerField()
    reader_id = models.IntegerField()
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)


class UserLib(models.Model):
    user_id = models.IntegerField()
    book_id = models.IntegerField()
    comment = models.TextField(blank=True)
    price = models.IntegerField(blank=False)

kitapsoresi/messenger/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import *


class AddBookForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].empty_label = "Автор не выбран"

    class Meta:
        model = Books
        fields = ['name', 'slug', 'description', 'photo', 'author', 'genre', 'price', 'is_published', ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-select'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'genre': forms.CheckboxSelectMultiple(attrs={'class': ''}),
            'price': forms.TextInput(attrs={'class': 'form-control'}),
        }

        def clean_name(self):
            name = self.cleaned_data['name']
            if len(name) > 100:
                raise ValidationError('Длина превышает 200 символов')
            return name


    # name = forms.CharField(max_length=255, label='Название', widget=forms.TextInput(attrs={'class': 'form-control'}))
    # slug = forms.SlugField(max_length=255, label='Слаг', widget=forms.TextInput(attrs={'class': 'form-control'}))
    # author = forms.ModelChoiceField(queryset=Author.objects.all(),
    #                                 label='Автор', empty_label="Выберите автора",
    #                                 widget=forms.Select(attrs={'class': 'form-select'}))
    # description = forms.CharField(label='Описание', widget=forms.TextInput(attrs={'class': 'form-control'}))
    # genre = forms.ModelMultipleChoiceField(queryset=Genre.objects.all(),
    #                                        widget=forms.CheckboxSelectMultiple(attrs={'class': ''}),
    #                                        label='Жанр')
    # price = forms.IntegerField(label='Цена', widget=forms.TextInput(attrs={'class': 'form-control'}))
    # is_published = forms.BooleanField(initial=True)

kitapsoresi/messenger/views.py
# from msilib.schema import ListView

from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from messenger.forms import AddBookForm
from messenger.models import Books, Genre, Author

menu = [
    {'title ': "Книги", 'url_name': 'books'},
    {'title': "О нас", 'url_name ': 'about'},
]


# Create your views here.

def index(request):
    context = {
        'title': 'General leaf',
        'menu': menu,
    }
    return render(request, 'messenger/index.html', context=context)


class BookHome(ListView):
    model = Books
    template_name = 'messenger/books.html'
    context_object_name = 'books'

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre_selected'] = 0
        context['author_selected'] = 0
        return context

    def get_queryset(self):
        return Books.objects.filter(is_published=True)


# def booksPage(requset):
#     books = Books.objects.all()
#     author = Author.objects.all()
#     context = {
#         'books': books,
#         'author': author,
#         'genre_selected': 0,
#         'author_selected': 0,
#         'menu': menu,
#     }
#     return render(requset, 'messenger/books.html', context=context)


class ShowBook(DetailView):
    model = Books
    template_name = 'messenger/book.html'
    slug_url_kwarg = 'book_slug'
    context_object_name = 'book'


# def show_book(request, book_slug):
#     book = get_object_or_404(Books, slug=book_slug)
#     context = {
#         'book': book,
#         'menu': menu,
#         # 'genre_selected': book.genre_id,
#     }
#
#     return render(request, 'messenger/book.html', context=context)


class BooksAuthor(ListView):
    model = Books
    template_name = 'messenger/books.html'
    context_object_name = 'books'
    allow_empty = True

    def get_queryset(self):
        return Books.objects.filter(author__slug=self.kwargs['author_slug'], is_published=True)

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre_selected'] = 0
        context['author_selected'] = context['books'][0].author_id
        return context


# def show_author(request, author_slug):
#     books = Books.objects.filter(author__slug=author_slug)
#     # genre = Genre.objects.all()
#     # author = Author.objects.all()
#     context = {
#         'books': books,
#         # 'genre': genre,
#         # 'author': author,
#         'menu': menu,
#         'author_selected': author_slug,
#     }
#     return render(request, 'messenger/books.html', context=context)

class BooksGenre(ListView):
    model = Books
    template_name = 'messenger/books.html'
    context_object_name = 'books'
    allow_empty = True

    def get_queryset(self):
        return Books.objects.filter(genre__slug=self.kwargs['genre_slug'], is_published=True)

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre_selected'] = 0
        context['author_selected'] = 0
        return context


# def show_genre(request, genre_slug):
#     books = Books.objects.filter(genre__slug=genre_slug)
#     # author = Author.objects.all()
#     context = {
#         'books': books,
#         # 'author': author,
#         'genre_selected': genre_slug,
#         'menu': menu,
#     }
#     return render(request, 'messenger/books.html', context=context)


def registrationPage(request):
    context = {
        'title': 'Registration Page',
        # 'menu':menu
    }
    return HttpResponseNotFound('<h1>Reg page</h1>')
    # return render(request, 'messenger/registrationPage.html', context=context)


class AddBook(CreateView):
    form_class = AddBookForm
    template_name = 'messenger/addbook.html'
    success_url = reverse_lazy('booksPage')


# def addbook(request):
#     if request.method == 'POST':
#         form = AddBookForm(request.POST, request.FILES)
#         if form.is_valid():
#             print(form.cleaned_data)
#             form.save()
#             return redirect('booksPage')
#     else:
#         form = AddBookForm()
#
#     return render(request, 'messenger/addbook.html', {'form': form})


def about(request):
    return HttpResponse('<h1>about</h1>')
    # return render(request, 'messenger/errors/500.html', status=500)


def categories(request, catid):
    return HttpResponse(f"<h1>Categories<br></h1>  <p>{catid}</p>")


def error400(request, exception):
    return HttpResponseNotFound('<h1>Page not found 400</h1>')
    # return render(request, 'messenger/errors/400.html', status=400)


def error403(request, exception):
    return HttpResponseNotFound('<h1>Page not found 403 </h1>')
    # return render(request, 'messenger/errors/403.html', status=403)


def error404(request, exception):
    return HttpResponseNotFound('<h1>Page not found 404</h1>')


def error500(request):
    return HttpResponseNotFound('<h1>Page not found 500</h1>')
    # return render(request, 'messenger/errors/500.html', status=500)

kitapsoresi/messenger/templates/messenger/about.html
{% extends 'messenger/base.html' %}
{%block content%}
{%load static%}

<div class="container mt-5 col-6 mx-auto">
    <h1>About us</h3>
</div>
<div class="box">

</div>
{%endblock%}

kitapsoresi/messenger/templates/messenger/addBookPage.html
{% extends 'messenger/base.html' %}

{% block content %}
<div class="container mt-5 col-6 mx-auto">
    <form action="{% url 'addBookPage' %}" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        <div>{{form.non_field_errors}}</div>

        {% for f in form %}
        <label for="{{ f.id_for_label }}">{{ f.label }}</label>
        <p>{{ f }}</p>
        <div>{{f.errors}}</div>
        {% endfor %}

        <button type="submit" class="btn btn-warning">Submit</button>
    </form>
</div>
{% endblock %}

kitapsoresi/messenger/templates/messenger/addbook.html
{%extends 'messenger/base.html' %}

{% block content%}


<div class="container mt-5 col-6 mx-auto">
    <h1>Добавление новой книги</h1>
    <form action="{% url 'addbook' %}" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        <div>{{form.non_field_errors}}</div>

        {% for f in form %}
        <label for="{{ f.id_for_label }}">{{ f.label }}</label>
            <p>{{ f }}</p>
        <div>
            {{f.errors}}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-warning">Submit</button>
    </form>
</div>

{%endblock%}

<!--{% if f.label == 'Жанр' %}-->
<!--        <label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}</label>-->
<!--        <div class="row">-->
<!--            {% for g in f %}-->
<!--            <div class="col-md-4">-->
<!--                <div class="form-check">-->
<!--                    <label class="form-check-label">-->
<!--                        {{ g }}-->
<!--                    </label>-->
<!--                </div>-->
<!--            </div>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--        {% else %}-->
<!--        <label for="{{ f.id_for_label }}">{{ f.label }}</label>-->
<!--        <p>{{ f }}</p>-->
<!--        {% endif %}-->

kitapsoresi/messenger/templates/messenger/base.html
{% load static %}
{% load messenger_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!--    <meta name="viewport" content="width = device-width">-->
    <meta name="viewport" content="width = 1170">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'messenger/css/style.css' %}" type="text/css">



    <title>
        {{title}}
    </title>
</head>
<body>
<nav class="navbar">
    <div class="container">
        <a href="{% url 'home' %}" class="brand"> Kitap Soresi</a>
        <div class="navbar-wrap">
            <ul class="navbar-menu">
                <li><a href="{% url 'booksPage' %}">Книги</a></li>
                <li><a href="">Поисковик</a></li>
                <li><a href="{% url 'addbook' %}">Add Book</a></li>
            </ul>
            <a href="" class="callback"> Регистрация</a>
            <div class="burger-menu">
                <button id="burger" class="burger-button btn btn-dark">
                    menu
                </button>
                <div id="menu" class="burger-slide disp">
                    <a class='nav-item block' href="{% url 'home' %}">ГЛАВНАЯ</a>
                    <a href="{% url 'booksPage' %}">Книги</a>
                    <a class='nav-item block' href="@">О НАС</a>
                    <a class='nav-item block' href="@">БРОНЬ</a>
                </div>
            </div>
        </div>
    </div>
</nav>

{%block content%}
{%endblock%}
<script>
    const burger = document.querySelector('#burger');
    const menu = document.querySelector('#menu');

    burger.addEventListener('click', () => {
        menu.classList.toggle('disp');
    });

</script>
</body>
</html>

kitapsoresi/messenger/templates/messenger/book.html
{% extends 'messenger/base.html' %}

{% block content %}

<section id="about" class="about section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-12 col-12">
                <div class="about-img">
                     <img class="book-picture" src="{{book.photo.url}}" width="450" class="img-fluid">
                </div>
            </div>
            <div class="col-lg-8 col-md-12 col-12 ps-lg-5 mt-md-5">
                <div class="about-text">
                    <h1>{{book.name}}</h1>
            <p> {{book.description | linebreaks}}</p>
                    <a href="#" class="btn btn-warning">Learn More</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!--<div class="container">-->
<!--  <div class="row">-->
<!--    <div class="col-12 col-md-6" style="background: black ; height: 500px ; ">-->
<!--      {% if book.photo %}-->
<!--       <img src="{{book.photo.url}}"   width="100%" alt="">-->
<!--      {% endif %}-->
<!--    </div>-->
<!--    <div class="col-12 col-md-6" style="background: yellow ; height: 500px">-->
<!--      <h1>{{book.title}}</h1>-->
<!--      {{book.description | linebreaks}}-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->


{% endblock %}

kitapsoresi/messenger/templates/messenger/books.html
{%extends 'messenger/base.html'%}
{%block content%}
{%load static%}
{% load messenger_tags %}

<div class="container mt-5">
    <div class="filter-container">
        <div class="filter">
            <h4>Фильтр</h4>
            <hr>
            <h5>По жанрам:</h5>

            {%if genre_selected == 0%}
            <li class="selected"> Все</li>
            {%else%}
            <li><a href="{%url 'booksPage'%}">Все </a></li>
            {%endif%}

            {% show_genres 'name' genre_selected %}
            <h5>По Авторам:</h5>
            {% show_authors 'name' author_selected %}
        </div>
        <div class="books-list">
            <div class="row row-cols-1 row-cols-md-4 row-cols-lg-5 g-4">
                {% for i in books %}
                <div class="col-6 col-md-6 col-lg-3">
                    <div class="card h-100">
                        {% if i.photo %}
                        <img src="{{i.photo.url}}" class="card-img-top" alt="...">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{i.name}}</h5>
                            <p class="card-text">{{i.author}}</p>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-primary btn-sm " href="{{ i.get_absolute_url }}">читать пост</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>


    </div>
</div>

{%endblock%}

kitapsoresi/messenger/templates/messenger/index.html
{%extends 'messenger/base.html'%}
{%block content%}
{%load static%}

<div class="container">
<div class="main">
    <div class="title">
        <h1 style="font-size:80px ; font-weight: bold; font-family: inter;">BOOKS FOR ALL</h1>
        <p>Lorem ipsum — классический текст-«рыба». Является искажённым отрывком из философского трактата Марка Туллия
            Цицерона «О пределах добра и зла»,</p>
        <button class="button-reg  btn btn-dark"    > Регистрация</button>
    </div>
    <div class="mainimage">
        <img src="{%static 'messenger/images/mainpic.svg'%}" width="90%">
    </div>
</div>
</div>

{%endblock%}

kitapsoresi/messenger/templates/messenger/list_categories.html
{% for c in cats %}
    {% if c.pk == cat_selected %}
        <li>{{c.name}}</li>
    {% else %}
    <li><a href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
    {% endif %}
{% endfor %}

kitapsoresi/messenger/templates/messenger/loginPage.html
{% extends 'messenger/base.html' %}
{%block content%}
<!--{%load static%}-->
<div class="container mt-5 col-6 mx-auto">

    <h1>{{title}}</h1>

    <form method="post">
        {% csrf_token %}
        <div>{{ form.non_field_errors }}</div>

        {% for f in form %}
        <label for="{{ f.id_for_label }}">{{f.label}}: </label>
        <p>{{ f }}</p>
        <div>{{ f.errors }}</div>
        {% endfor %}

        <button type="submit" class="btn btn-warning">Авторизация</button>
    </form>
</div>
{%endblock%}

<!--<div>-->
<!--    <h3>Login</h3>-->
<!--</div>-->
<!--<div class="box">-->
<!--    <form>-->
<!--        <input type="email" placeholder="email"><br>-->
<!--        <input type="password" placeholder="password"><br>-->
<!--        <input type="submit" value="Login"><br>-->
<!--        <a href="{%url 'registrationPage'%}">Do not have an account?</a>-->
<!--    </form>-->
<!--</div>-->

kitapsoresi/messenger/templates/messenger/registrationPage.html
{% extends 'messenger/base.html' %}
{%block content%}
<!--{%load static%}-->
<div class="container mt-5 col-6 mx-auto">

    <h1>{{title}}</h1>

    <form method="post">
        {% csrf_token %}
        <div>{{ form.non_field_errors }}</div>

        {% for f in form %}
        <label for="{{ f.id_for_label }}">{{f.label}}: </label>
        <p>{{ f }}</p>
        <div>{{ f.errors }}</div>
        {% endfor %}

        <button type="submit" class="btn btn-warning">Регистрация</button>
    </form>
</div>

{%endblock%}

kitapsoresi/messenger/templates/messenger/searchPage.html
{% extends 'messenger/base.html' %}
{%block content%}
{%load static%}

<div class="container mt-5 col-6 mx-auto">
    <h1>Search Page</h1>
</div>
<div class="box">

</div>
{%endblock%}

kitapsoresi/messenger/templates/messenger/userPage.html
{% extends 'messenger/base.html' %}
{%block content%}
{%load static%}

<div class="container mt-5 col-6 mx-auto">
    <h1>User Page</h1>
</div>
<div class="box">

</div>
{%endblock%}

kitapsoresi/messenger/templates/messenger/user_books.html
{% extends 'messenger/base.html' %}
{% block content %}
{% load static %}
{% load messenger_tags %}

<div class="container mt-5">

<!--    Filter-->
    <div class="filter-container">
        <div class="filter">
            <h4>Фильтр</h4>
            <hr>
            <h5>По жанрам:</h5>
            {% if genre_selected == 0 %}
            <li class="selected"> Все жанры </li>
            {% else %}
            <li><a href="{%url 'booksPage'%}">Все жанры </a></li>
            {% endif %}

            {% for g in genres %}
                {% if g.books__count > 0 %}
                    {% if g.pk == genre_selected %}
                        <li class="selected">{{g.name}} </li>
                    {% else %}
                        <li><a href="{{ g.get_absolute_url }}">{{g.name}}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}

<!--            <h5>По Авторам:</h5>-->
<!--            {% show_authors 'name' author_selected %}-->
        </div>

        <div class="books-list">
            <div class="row row-cols-1 row-cols-md-4 row-cols-lg-5 g-4">
                {% for i in books %}
                    <div class="col-6 col-md-6 col-lg-3">
                        <div class="card h-100">
                            {% if i.photo %}
                            <img src="{{i.photo.url}}" class="card-img-top" alt="...">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{i.name}}</h5>
                                <p class="card-text">{{i.author}}</p>
                                <p class="card-text">{{genres.i.genre}}</p>
                                <p class="card-text">{{i.user}}</p>
                                <p class="card-text">{{i.book}}</p>
                            </div>
                            <div class="card-footer">
                                <a class="btn btn-primary btn-sm " href="{{ i.get_absolute_url }}">Подробнее</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>


    </div>
</div>

{%endblock%}

kitapsoresi/messenger/templates/messenger/user_wishList.html
{% extends 'messenger/base.html' %}
{% block content %}
{% load static %}
{% load messenger_tags %}

<div class="container mt-5">

        <div class="books-list">
            <div class="row row-cols-1 row-cols-md-4 row-cols-lg-5 g-4">
                {% for b in books_list %}
<!--                    {% if wish_list == Null %}-->
<!--                            <h3>You don't have wish-books yet</h3>-->
<!--                    {% endif %}-->
                    {% for w in wish_list %}
                        {% if b.slug == w.book_slug %}
                            <div class="col-6 col-md-6 col-lg-3">
                                <div class="card h-100">
                                    {% if b.photo %}
                                        <img src="{{b.photo.url}}" class="card-img-top" alt="...">
                                    {% endif %}

                                    <div class="card-body">
                                        <p>{{b.name}}</p>
                                        <p>{{b.slug}}</p>
                                        <p>{{b.price}}</p>
                                        <p>{{b.author}}</p>
                                    </div>

                                    <div class="card-footer">
                                        <a class="btn btn-primary btn-sm " href="{{ b.get_absolute_url }}">Подробнее</a>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{%endblock%}